export default  {
    "message": " Order Uploaded Successfully",
    "status": 200,
    "data": [
      {
        "check_gate_tested": 119,
        "health_facilities_tested": 201,
        
        "tested": 320,
        "tested_negative": 320,
        "tested_positive": 0,
        "cured": 16,
        "death": 0,
        "cumulative_positive": 1913,
        "cumulative_cured": 1798,
        "active_case": 100,
        "cumulative_deaths": 15,

        "covid_hospitals": 0,
        "covid_hospital_beds": 0,
        "covid_hospital_admitted": 0,
        "covid_hospital_icu_beds": 0,
        "covid_hospitals_icu_bed_occupied": 0,
        "covid_hospital_o2_beds": 0,
        "covid_hospital_o2_bed_occupied": 0,
        "covid_hospital_non_o2_beds": 0,
        "covid_hospital_non_o2_bed_occupied": 0,

        "dchc": 1,
        "dchc_beds": 36,
        "dchc_admitted": 0,
        "dchc_icu_beds": 0,
        "dchc_icu_beds_occupied": 0,
        "dchc_o2_beds": 36,
        "dchc_o2_occupied": 0,
        "dchc_non_o2_beds": 0,
        "dchc_non_o2_beds_occupied": 0,

        "ccc": 1,
        "ccc_beds": 36,
        "ccc_admitted": 3,
        "home_isolation": 97,

        "flw_1st_dose_received": 0,
        "flw_fully_inoculated": 0,
        "hcw_1st_dose_received": 0,
        "hcw_fully_inoculated": 0,
        "45years_fully_inoculated": 0,
        "45years_1st_dose_received": 0,
        "18_to_44years_received_1st_dose": 0,
        "18_to_44years_fully_inoculated": 0,
        "total_registered_for_vaccination": 0,

        "total_received_1st_dose": 56308,
        "total_fully_inoculated": 11159,
        
        "date": "2021-08-01T18:30:00.000Z",

        "ccc_o2_beds": 0,
        "ccc_o2_occupied": 0,
        "ccc_non_o2_beds": 36,
        "ccc_non_o2_occupied": 3,
        "cumulative_tested": 59090,
        
        "violations_reported_today": 0,
        "cumulative_violations_reported": 1761,
        "fine_imposed_today": 0,
        "cumulative_fine_imposed": 341065
      },
      {
        "check_gate_tested": 7,
        "health_facilities_tested": 16,
        "tested": 23,
        "tested_negative": 22,
        "tested_positive": 1,
        "cured": 1,
        "death": 0,
        "cumulative_positive": 382,
        "cumulative_cured": 362,
        "active_case": 20,
        "cumulative_deaths": 0,
        "covid_hospitals": 0,
        "covid_hospital_beds": 0,
        "covid_hospital_admitted": 0,
        "covid_hospital_icu_beds": 0,
        "covid_hospitals_icu_bed_occupied": 0,
        "covid_hospital_o2_beds": 0,
        "covid_hospital_o2_bed_occupied": 0,
        "covid_hospital_non_o2_beds": 0,
        "covid_hospital_non_o2_bed_occupied": 0,
        "dchc": 0,
        "dchc_beds": 0,
        "dchc_admitted": 0,
        "dchc_icu_beds": 0,
        "dchc_icu_beds_occupied": 0,
        "dchc_o2_beds": 0,
        "dchc_o2_occupied": 0,
        "dchc_non_o2_beds": 0,
        "dchc_non_o2_beds_occupied": 0,
        "ccc": 2,
        "ccc_beds": 20,
        "ccc_admitted": 0,
        "home_isolation": 20,
        "flw_1st_dose_received": 0,
        "flw_fully_inoculated": 0,
        "hcw_1st_dose_received": 0,
        "hcw_fully_inoculated": 0,
        "45years_fully_inoculated": 0,
        "45years_1st_dose_received": 0,
        "18_to_44years_received_1st_dose": 0,
        "18_to_44years_fully_inoculated": 0,
        "total_registered_for_vaccination": 0,
        "total_received_1st_dose": 6991,
        "total_fully_inoculated": 2765,
        "date": "2021-08-01T18:30:00.000Z",
        "ccc_o2_beds": 0,
        "ccc_o2_occupied": 0,
        "ccc_non_o2_beds": 20,
        "ccc_non_o2_occupied": 0,
        "cumulative_tested": 8389,
        "violations_reported_today": 0,
        "cumulative_violations_reported": 101,
        "fine_imposed_today": 0,
        "cumulative_fine_imposed": 17670
      }
    ],
    "success": true
  }